//! In-depth explanation engine for Magento Doctor rules.

pub struct RuleExplanation {
    pub rule_id: &'static str,
    pub title: &'static str,
    pub what: &'static str,
    pub why_affected: &'static str,
    pub detection_mechanism: &'static str,
    pub false_positives: &'static str,
    pub verification: &'static str,
    pub remediation: &'static str,
}

pub const RULE_EXPLANATIONS: &[RuleExplanation] = &[
    RuleExplanation {
        rule_id: "MD-CRON-001",
        title: "Cron Backlog in cron_schedule",
        what: "The cron_schedule table contains an unusually high number of pending or stuck running jobs.",
        why_affected: "Magento relies on its internal cron engine for vital asynchronous operations: reindexing changelogs (MView), updating catalog prices, sending transactional order emails, customer alerts, and clearing visitors. When cron falls behind, catalog updates stop reflecting on storefronts and database locks accumulate.",
        detection_mechanism: "Queries cron_schedule for rows in 'pending' status older than schedule threshold, or jobs in 'running' status with execution times exceeding 15 minutes.",
        false_positives: "Rare. A single massive one-off data migration script running via cron can temporarily display as stuck running.",
        verification: "Run in MySQL:\n  SELECT job_code, status, scheduled_at, executed_at FROM cron_schedule WHERE status = 'running' ORDER BY executed_at ASC;\nOr test manually:\n  bin/magento cron:run -vvv",
        remediation: "1. Terminate orphaned stuck PHP processes.\n2. Delete stale running rows from cron_schedule.\n3. Verify system crontab (* * * * * php /path/bin/magento cron:run) runs under the correct web/CLI user.",
    },
    RuleExplanation {
        rule_id: "MD-CRON-010",
        title: "Cron Job Overlap Storm",
        what: "A scheduled job's observed execution duration exceeds its scheduling interval (e.g. interval = 60s, median runtime = 74s).",
        why_affected: "When a job runs longer than its frequency interval, subsequent cron runs spawn new overlapping instances before previous instances finish. These concurrent instances fight for the same database locks and CPU cores, creating exponential load.",
        detection_mechanism: "Compares declared schedule interval in crontab.xml against median/P95 execution durations in cron_schedule, calculating overlap_ratio = runtime / interval. Correlates with PHP AST to identify heavy loops or HTTP calls.",
        false_positives: "Low. If historical runtime data is skewed by an isolated external API outage, runtime may be temporarily inflated.",
        verification: "Inspect historical executions:\n  SELECT job_code, status, executed_at, finished_at, TIMESTAMPDIFF(SECOND, executed_at, finished_at) AS dur\n  FROM cron_schedule WHERE job_code = 'YOUR_JOB' AND status = 'success'\n  ORDER BY executed_at DESC LIMIT 20;",
        remediation: "1. Decrease frequency in etc/crontab.xml (e.g. change '* * * * *' to '*/15 * * * *').\n2. Move heavy remote API integrations or exports to asynchronous queues.\n3. Implement execution locking in PHP to prevent concurrent execution.",
    },
    RuleExplanation {
        rule_id: "MD-PLG-001",
        title: "Around Plugin on Critical Hot Path",
        what: "An 'around' plugin intercepts a high-frequency Magento core method (such as QuoteManagement::submit or Product::getPrice).",
        why_affected: "Adobe's extension documentation explicitly discourages 'around' plugins where 'before' or 'after' plugins suffice. Around plugins construct additional call stacks and closure allocations. On hot paths, especially checkout or product loops, this multiplies response latency and introduces fatal recursion risks if $proceed is mishandled.",
        detection_mechanism: "Cross-checks di.xml plugin declarations against Magento Doctor's curated hot-path database and analyzes the plugin class AST for loops, database writes, or outbound network calls.",
        false_positives: "None on the presence of the around plugin. The actual impact depends on storefront traffic volume.",
        verification: "Check plugin declaration:\n  grep -rn \"QuoteManagement\" app/code/ vendor/ --include=di.xml",
        remediation: "Refactor the plugin into a 'before' or 'after' plugin. If arguments or return values must be altered, use before* or after* hooks.",
    },
    RuleExplanation {
        rule_id: "MD-PERF-021",
        title: "N+1 Repository Access in Collection Loop",
        what: "A repository load (e.g. $categoryRepository->getById() or $productRepository->getById()) is executed inside a foreach/while loop over a collection or array.",
        why_affected: "Calling getById() inside a loop causes Magento to execute a fresh database query (and multiple EAV joins) for every single item in the collection. For 1,000 items, this triggers 1,000 distinct SQL queries instead of 1 batched query.",
        detection_mechanism: "Tree-sitter PHP AST analysis walks the syntax tree, tracks loop depth, captures exact file paths and line numbers, and flags member call expressions on repository instances within loop blocks.",
        false_positives: "Very low. In rare cases, a loop with a hardcoded limit of 1 or 2 iterations might trigger a warning.",
        verification: "Inspect the flagged source file and line number. Enable MySQL query logging or Magento DB profiler during that execution.",
        remediation: "Refactor to batch-load entities before entering the loop:\n  1. Pre-collect entity IDs: $ids = array_unique(array_filter($itemIds));\n  2. Batch-load via CollectionFactory (->addAttributeToFilter('entity_id', ['in' => $ids])) or SearchCriteriaBuilder with 'in' filter.\n  3. Pre-map into an associative lookup array ($itemsById[$id] = $item) for O(1) in-memory resolution inside the loop.",
    },
    RuleExplanation {
        rule_id: "MD-DB-001",
        title: "Missing Declared Database Index",
        what: "A table index defined in a module's db_schema.xml is missing from the physical database table.",
        why_affected: "When an index is missing, MySQL must scan entire tables or use unindexed temporary filesorts for queries that developers expected to be indexed.",
        detection_mechanism: "Compares declared indexes in all active modules' db_schema.xml against information_schema.statistics.",
        false_positives: "None. If the index is in db_schema.xml and missing from MySQL, declarative schema was not applied.",
        verification: "Run in MySQL:\n  SHOW INDEX FROM <table>;",
        remediation: "Run 'bin/magento setup:db-declaration:generate-whitelist' followed by 'bin/magento setup:upgrade'.",
    },
    RuleExplanation {
        rule_id: "MD-CACHE-001",
        title: "Redis Session and Cache Database Collision",
        what: "Redis session storage and default application cache or full page cache are configured to use the exact same database number on the same Redis host/instance.",
        why_affected: "In Redis, FLUSHDB flushes the entire numbered database. If sessions and cache share DB 0 on the same instance, running 'bin/magento cache:flush' immediately purges all customer sessions, logging out shoppers and abandoning active carts.",
        detection_mechanism: "Inspects Redis database numbers and host/port endpoints configured under 'session' and 'cache' in app/etc/env.php. Separate Redis host instances using the same database number are verified and allowed.",
        false_positives: "None.",
        verification: "Inspect app/etc/env.php session and cache sections.",
        remediation: "Assign distinct database numbers in app/etc/env.php (e.g. DB 0 for default cache, DB 1 for page_cache, DB 2 for session) or point them to separate Redis instances/ports.",
    },
    RuleExplanation {
        rule_id: "MD-DB-004",
        title: "Unsupported MySQL or MariaDB Version",
        what: "The database server version is not certified or supported for this Magento release.",
        why_affected: "Incompatible database versions cause SQL syntax errors, query planner regressions, unexpected collation coercion, or replication failure.",
        detection_mechanism: "Compares live @@version or snapshot server_version against Magento Doctor's supported version matrix for MySQL (8.0, 8.4 LTS, 9.x) and MariaDB (10.4, 10.6, 10.11, 11.x).",
        false_positives: "None when the server version string accurately reflects the database engine.",
        verification: "Run in MySQL:\n  SELECT VERSION();",
        remediation: "Upgrade or downgrade your database server to a version supported by Adobe's system requirements for this Magento release.",
    },
    RuleExplanation {
        rule_id: "MD-CACHE-003",
        title: "Unsupported Redis or Valkey Version",
        what: "The Redis or Valkey server version falls outside the supported compatibility matrix for this Magento release.",
        why_affected: "Running an untested cache server version risks command protocol incompatibilities, memory eviction anomalies, or unexpected key expiration behaviors.",
        detection_mechanism: "Queries INFO server against configured Redis/Valkey endpoints and cross-checks with Magento Doctor's version matrix.",
        false_positives: "Low.",
        verification: "Run in terminal:\n  redis-cli INFO server | grep redis_version\nOr for Valkey:\n  valkey-cli INFO server",
        remediation: "Align Redis or Valkey with supported versions: Redis 7.0/7.2/8.0 or Valkey 7.2/8.0.",
    },
    RuleExplanation {
        rule_id: "MD-ENV-003",
        title: "Unsupported OpenSearch Version",
        what: "The configured OpenSearch cluster version is not certified for this Magento release.",
        why_affected: "Catalog search, Elasticsearch/OpenSearch adapter modules, and faceted filtering depend on specific query DSL formats and index mapping schemas supported by particular OpenSearch releases.",
        detection_mechanism: "Queries OpenSearch root endpoint (GET /) and compares 'version.number' against the Magento compatibility matrix.",
        false_positives: "None.",
        verification: "Run in terminal:\n  curl -s http://localhost:9200/",
        remediation: "Deploy a certified OpenSearch version (e.g. OpenSearch 2.12, 2.19, or 3.0) and reindex catalogsearch_fulltext.",
    },
    RuleExplanation {
        rule_id: "MD-SQL-001",
        title: "High Latency MySQL Query Digest Detected",
        what: "A normalized query fingerprint is repeatedly executing with average execution duration > 1,000ms or scanning > 50,000 rows.",
        why_affected: "Unindexed or poorly constructed queries saturate MySQL thread pools, generate lock waits, and cause cascading PHP-FPM worker exhaustion that produces storefront 504 timeouts.",
        detection_mechanism: "Queries performance_schema.events_statements_summary_by_digest, parses query fingerprints, extracts table references, and correlates with owning modules.",
        false_positives: "Very low. Queries with high average latency under sustained traffic are confirmed performance bottlenecks.",
        verification: "Run in MySQL:\n  EXPLAIN <query>;\nCheck query plan for 'ALL' (full table scan) or 'Using filesort'.",
        remediation: "Add missing composite indexes to cover WHERE and ORDER BY columns, avoid leading wildcards in LIKE queries, or cache query results.",
    },
    RuleExplanation {
        rule_id: "MD-SQL-002",
        title: "Active MySQL Lock Contention",
        what: "Queries are actively blocked waiting for row locks or table metadata locks for longer than 5 seconds.",
        why_affected: "Long-running transactions hold locks that queue incoming customer requests, leading to severe thread pool exhaustion.",
        detection_mechanism: "Queries information_schema.processlist and innodb lock wait tables for active lock states.",
        false_positives: "None. Blocked queries exceeding 5s are active production bottlenecks.",
        verification: "Run in MySQL:\n  SHOW FULL PROCESSLIST;\n  SHOW ENGINE INNODB STATUS;",
        remediation: "Terminate blocking connections, minimize transaction scope, and avoid mixing DDL statements with active storefront traffic.",
    },
    RuleExplanation {
        rule_id: "MD-RDS-001",
        title: "Redis Session Store Configured with Eviction",
        what: "The Redis instance storing PHP sessions is configured with a memory eviction policy (e.g. allkeys-lru, volatile-lru) or has recorded evicted keys.",
        why_affected: "Unlike cache data, customer sessions must NEVER be evicted. Evicting session keys destroys active carts, logs out customers during checkout, and loses order state.",
        detection_mechanism: "Queries Redis INFO for maxmemory_policy and evicted_keys on the session endpoint.",
        false_positives: "None.",
        verification: "Run in terminal:\n  redis-cli -p <session_port> CONFIG GET maxmemory-policy\n  redis-cli -p <session_port> INFO stats | grep evicted_keys",
        remediation: "Set maxmemory_policy to 'noeviction' in redis.conf and ensure the session Redis instance has sufficient dedicated memory.",
    },
    RuleExplanation {
        rule_id: "MD-FPM-001",
        title: "PHP-FPM Worker Pool Saturation",
        what: "Active PHP-FPM workers exceed 85% of pm.max_children or the listen queue has queued connections.",
        why_affected: "When all workers are busy, incoming web traffic queues up. If requests wait longer than Nginx proxy_read_timeout, visitors receive 504 Gateway Timeouts.",
        detection_mechanism: "Inspects running PHP-FPM process states and pool configuration parameters.",
        false_positives: "Low. Sustained queue length > 0 is an immediate sign of worker starvation.",
        verification: "Check worker count:\n  ps aux | grep php-fpm | grep -v grep | wc -l\nOr inspect PHP-FPM status page.",
        remediation: "Increase pm.max_children if memory permits, or optimize slow database queries and external HTTP calls holding workers open.",
    },
    RuleExplanation {
        rule_id: "MD-FPC-001",
        title: "Storefront Layout FPC Puncture (cacheable=\"false\")",
        what: "A storefront layout XML file (catalog, cms, or default handle) contains a <block> declared with cacheable=\"false\".",
        why_affected: "In Magento 2, setting cacheable=\"false\" on ANY block in a layout file completely disables Full Page Cache for that entire page. Every visitor hit triggers full PHP bootstrapping and tens of database queries.",
        detection_mechanism: "Parses all layout XML files in active modules and themes, flagging blocks with cacheable=\"false\" in storefront handles.",
        false_positives: "None. Adobe documentation strictly forbids cacheable=\"false\" on cacheable page types.",
        verification: "Run in terminal:\n  curl -I -H 'X-Magento-Cache-Debug: 1' https://your-store.com/catalog/product/view/id/1\nVerify whether X-Magento-Cache-Debug is 'MISS' on repeated hits.",
        remediation: "Remove cacheable=\"false\" from the layout XML. Move customer-specific content to customer-data.js (private session data) or load it asynchronously via GraphQL.",
    },
    RuleExplanation {
        rule_id: "MD-SRC-001",
        title: "OpenSearch Cluster Health Degraded",
        what: "OpenSearch cluster health is 'red' or 'yellow', or unassigned shards are present.",
        why_affected: "A red cluster cannot execute search or aggregation queries, causing 500 errors across all category and product listing pages. Yellow status indicates lost replica redundancy.",
        detection_mechanism: "Queries GET /_cluster/health and verifies status and unassigned_shards count.",
        false_positives: "None.",
        verification: "Run in terminal:\n  curl http://localhost:9200/_cluster/health?pretty",
        remediation: "Investigate unassigned shards via GET /_cluster/allocation/explain?pretty and check disk space on Elasticsearch/OpenSearch data nodes.",
    },
];

pub fn get_rule_explanation(rule_id: &str) -> Option<&'static RuleExplanation> {
    RULE_EXPLANATIONS.iter().find(|e| e.rule_id.eq_ignore_ascii_case(rule_id))
}
