//! In-depth explanation engine for Magento Doctor rules.

pub struct RuleExplanation {
    pub rule_id: &'static str,
    pub title: &'static str,
    pub what: &'static str,
    pub why_affected: &'static str,
    pub detection_mechanism: &'static str,
    pub false_positives: &'static str,
    pub verification: &'static str,
    pub remediation: &'static str,
}

pub const RULE_EXPLANATIONS: &[RuleExplanation] = &[
    RuleExplanation {
        rule_id: "MD-CRON-001",
        title: "Cron Backlog in cron_schedule",
        what: "The cron_schedule table contains an unusually high number of pending or stuck running jobs.",
        why_affected: "Magento relies on its internal cron engine for vital asynchronous operations: reindexing changelogs (MView), updating catalog prices, sending transactional order emails, customer alerts, and clearing visitors. When cron falls behind, catalog updates stop reflecting on storefronts and database locks accumulate.",
        detection_mechanism: "Queries cron_schedule for rows in 'pending' status older than schedule threshold, or jobs in 'running' status with execution times exceeding 15 minutes.",
        false_positives: "Rare. A single massive one-off data migration script running via cron can temporarily display as stuck running.",
        verification: "Run in MySQL:\n  SELECT job_code, status, scheduled_at, executed_at FROM cron_schedule WHERE status = 'running' ORDER BY executed_at ASC;\nOr test manually:\n  bin/magento cron:run -vvv",
        remediation: "1. Terminate orphaned stuck PHP processes.\n2. Delete stale running rows from cron_schedule.\n3. Verify system crontab (* * * * * php /path/bin/magento cron:run) runs under the correct web/CLI user.",
    },
    RuleExplanation {
        rule_id: "MD-CRON-010",
        title: "Cron Job Overlap Storm",
        what: "A scheduled job's observed execution duration exceeds its scheduling interval (e.g. interval = 60s, median runtime = 74s).",
        why_affected: "When a job runs longer than its frequency interval, subsequent cron runs spawn new overlapping instances before previous instances finish. These concurrent instances fight for the same database locks and CPU cores, creating exponential load.",
        detection_mechanism: "Compares declared schedule interval in crontab.xml against median/P95 execution durations in cron_schedule, calculating overlap_ratio = runtime / interval. Correlates with PHP AST to identify heavy loops or HTTP calls.",
        false_positives: "Low. If historical runtime data is skewed by an isolated external API outage, runtime may be temporarily inflated.",
        verification: "Inspect historical executions:\n  SELECT job_code, status, executed_at, finished_at, TIMESTAMPDIFF(SECOND, executed_at, finished_at) AS dur\n  FROM cron_schedule WHERE job_code = 'YOUR_JOB' AND status = 'success'\n  ORDER BY executed_at DESC LIMIT 20;",
        remediation: "1. Decrease frequency in etc/crontab.xml (e.g. change '* * * * *' to '*/15 * * * *').\n2. Move heavy remote API integrations or exports to asynchronous queues.\n3. Implement execution locking in PHP to prevent concurrent execution.",
    },
    RuleExplanation {
        rule_id: "MD-PLG-001",
        title: "Around Plugin on Critical Hot Path",
        what: "An 'around' plugin intercepts a high-frequency Magento core method (such as QuoteManagement::submit or Product::getPrice).",
        why_affected: "Adobe's extension documentation explicitly discourages 'around' plugins where 'before' or 'after' plugins suffice. Around plugins construct additional call stacks and closure allocations. On hot paths, especially checkout or product loops, this multiplies response latency and introduces fatal recursion risks if $proceed is mishandled.",
        detection_mechanism: "Cross-checks di.xml plugin declarations against Magento Doctor's curated hot-path database and analyzes the plugin class AST for loops, database writes, or outbound network calls.",
        false_positives: "None on the presence of the around plugin. The actual impact depends on storefront traffic volume.",
        verification: "Check plugin declaration:\n  grep -rn \"QuoteManagement\" app/code/ vendor/ --include=di.xml",
        remediation: "Refactor the plugin into a 'before' or 'after' plugin. If arguments or return values must be altered, use before* or after* hooks.",
    },
    RuleExplanation {
        rule_id: "MD-PERF-021",
        title: "N+1 Repository Access in Collection Loop",
        what: "A repository load (e.g. $categoryRepository->getById() or $productRepository->getById()) is executed inside a foreach/while loop over a collection or array.",
        why_affected: "Calling getById() inside a loop causes Magento to execute a fresh database query (and multiple EAV joins) for every single item in the collection. For 1,000 items, this triggers 1,000 distinct SQL queries instead of 1 batched query.",
        detection_mechanism: "Tree-sitter PHP AST analysis walks the syntax tree, tracks loop depth, captures exact file paths and line numbers, and flags member call expressions on repository instances within loop blocks.",
        false_positives: "Very low. In rare cases, a loop with a hardcoded limit of 1 or 2 iterations might trigger a warning.",
        verification: "Inspect the flagged source file and line number. Enable MySQL query logging or Magento DB profiler during that execution.",
        remediation: "Refactor to batch-load entities before entering the loop:\n  1. Pre-collect entity IDs: $ids = array_unique(array_filter($itemIds));\n  2. Batch-load via CollectionFactory (->addAttributeToFilter('entity_id', ['in' => $ids])) or SearchCriteriaBuilder with 'in' filter.\n  3. Pre-map into an associative lookup array ($itemsById[$id] = $item) for O(1) in-memory resolution inside the loop.",
    },
    RuleExplanation {
        rule_id: "MD-DB-001",
        title: "Missing Declared Database Index",
        what: "A table index defined in a module's db_schema.xml is missing from the physical database table.",
        why_affected: "When an index is missing, MySQL must scan entire tables or use unindexed temporary filesorts for queries that developers expected to be indexed.",
        detection_mechanism: "Compares declared indexes in all active modules' db_schema.xml against information_schema.statistics.",
        false_positives: "None. If the index is in db_schema.xml and missing from MySQL, declarative schema was not applied.",
        verification: "Run in MySQL:\n  SHOW INDEX FROM <table>;",
        remediation: "Run 'bin/magento setup:db-declaration:generate-whitelist' followed by 'bin/magento setup:upgrade'.",
    },
    RuleExplanation {
        rule_id: "MD-CACHE-001",
        title: "Redis Session and Cache Database Collision",
        what: "Redis session storage and default application cache or full page cache are configured to use the exact same database number on the same Redis host/instance.",
        why_affected: "In Redis, FLUSHDB flushes the entire numbered database. If sessions and cache share DB 0 on the same instance, running 'bin/magento cache:flush' immediately purges all customer sessions, logging out shoppers and abandoning active carts.",
        detection_mechanism: "Inspects Redis database numbers and host/port endpoints configured under 'session' and 'cache' in app/etc/env.php. Separate Redis host instances using the same database number are verified and allowed.",
        false_positives: "None.",
        verification: "Inspect app/etc/env.php session and cache sections.",
        remediation: "Assign distinct database numbers in app/etc/env.php (e.g. DB 0 for default cache, DB 1 for page_cache, DB 2 for session) or point them to separate Redis instances/ports.",
    },
    RuleExplanation {
        rule_id: "MD-DB-004",
        title: "Unsupported MySQL or MariaDB Version",
        what: "The database server version is not certified or supported for this Magento release.",
        why_affected: "Incompatible database versions cause SQL syntax errors, query planner regressions, unexpected collation coercion, or replication failure.",
        detection_mechanism: "Compares live @@version or snapshot server_version against Magento Doctor's supported version matrix for MySQL (8.0, 8.4 LTS, 9.x) and MariaDB (10.4, 10.6, 10.11, 11.x).",
        false_positives: "None when the server version string accurately reflects the database engine.",
        verification: "Run in MySQL:\n  SELECT VERSION();",
        remediation: "Upgrade or downgrade your database server to a version supported by Adobe's system requirements for this Magento release.",
    },
    RuleExplanation {
        rule_id: "MD-CACHE-003",
        title: "Unsupported Redis or Valkey Version",
        what: "The Redis or Valkey server version falls outside the supported compatibility matrix for this Magento release.",
        why_affected: "Running an untested cache server version risks command protocol incompatibilities, memory eviction anomalies, or unexpected key expiration behaviors.",
        detection_mechanism: "Queries INFO server against configured Redis/Valkey endpoints and cross-checks with Magento Doctor's version matrix.",
        false_positives: "Low.",
        verification: "Run in terminal:\n  redis-cli INFO server | grep redis_version\nOr for Valkey:\n  valkey-cli INFO server",
        remediation: "Align Redis or Valkey with supported versions: Redis 7.0/7.2/8.0 or Valkey 7.2/8.0.",
    },
    RuleExplanation {
        rule_id: "MD-ENV-003",
        title: "Unsupported OpenSearch Version",
        what: "The configured OpenSearch cluster version is not certified for this Magento release.",
        why_affected: "Catalog search, Elasticsearch/OpenSearch adapter modules, and faceted filtering depend on specific query DSL formats and index mapping schemas supported by particular OpenSearch releases.",
        detection_mechanism: "Queries OpenSearch root endpoint (GET /) and compares 'version.number' against the Magento compatibility matrix.",
        false_positives: "None.",
        verification: "Run in terminal:\n  curl -s http://localhost:9200/",
        remediation: "Deploy a certified OpenSearch version (e.g. OpenSearch 2.12, 2.19, or 3.0) and reindex catalogsearch_fulltext.",
    },
    RuleExplanation {
        rule_id: "MD-SQL-001",
        title: "High Latency MySQL Query Digest Detected",
        what: "A normalized query fingerprint is executing with average duration > 1,000ms, or scanning > 50,000 rows on average.",
        why_affected: "Unindexed or poorly constructed queries saturate MySQL thread pools, generate lock waits, and cause cascading PHP-FPM worker exhaustion that produces storefront 504 timeouts.",
        detection_mechanism: "Queries performance_schema.events_statements_summary_by_digest filtered to this store's schema, parses query fingerprints, extracts table references, and correlates with owning modules.",
        false_positives: "Digests are cumulative since the server last started, so a one-off maintenance query (a reindex, a bulk import, an admin report) can raise the average long after it finished. A digest that is wide but fast is reported as a Warning rather than Critical for that reason. Check LAST_SEEN before acting.",
        verification: "Substitute literal values for the ? placeholders in the fingerprint, then run:\n  EXPLAIN ANALYZE <query>;\nCheck the plan for a full table scan or 'Using filesort'.",
        remediation: "Add composite indexes covering the WHERE and ORDER BY columns, avoid leading wildcards in LIKE queries, or cache the result.",
    },
    RuleExplanation {
        rule_id: "MD-SQL-002",
        title: "Active MySQL Transaction Lock Wait",
        what: "performance_schema.data_lock_waits names a transaction blocked behind another transaction's lock for longer than 5 seconds.",
        why_affected: "Long-running transactions hold locks that queue incoming customer requests, leading to thread pool exhaustion and 504s at the web tier.",
        detection_mechanism: "Joins performance_schema.data_lock_waits against information_schema.innodb_trx so both the blocked and the blocking transaction are identified. Replication, daemon and event-scheduler threads are excluded.",
        false_positives: "Low. This rule fires only on a confirmed blocker/blocked pair, never on a query that is merely slow (that is MD-SQL-003). A lock wait during a deliberate maintenance window is expected.",
        verification: "Run in MySQL:\n  SELECT * FROM performance_schema.data_lock_waits;\n  SHOW ENGINE INNODB STATUS;",
        remediation: "Terminate the blocking connection, minimize transaction scope, and avoid mixing DDL statements with live storefront traffic.",
    },
    RuleExplanation {
        rule_id: "MD-SQL-003",
        title: "Long-Running MySQL Statement Occupying a Connection",
        what: "A statement in the processlist has been executing for more than 5 seconds against this store's schema, with no blocking transaction identified.",
        why_affected: "A statement that runs for seconds holds a PHP worker open for the same duration. It is not lock contention, so the fix is the query itself rather than a blocking transaction.",
        detection_mechanism: "Reads information_schema.processlist excluding mdoctor's own connection, Sleep, Binlog Dump, Daemon and Connect commands, and the 'system user' and 'event_scheduler' accounts, which otherwise appear with TIME equal to server uptime.",
        false_positives: "Moderate. Legitimate long jobs — reindexing, bulk imports, analytics queries — appear here. Compare against what you expect to be running.",
        verification: "Run in MySQL:\n  SHOW FULL PROCESSLIST;",
        remediation: "Optimize or paginate the statement, or move the workload off the request path into a consumer or cron job.",
    },
    RuleExplanation {
        rule_id: "MD-RDS-001",
        title: "Redis Session Store Can Evict Live Customer Sessions",
        what: "The Redis instance holding PHP sessions uses an allkeys-* eviction policy, or has evicted keys on an instance dedicated to sessions.",
        why_affected: "Magento sets a TTL on every session key. A volatile-* policy therefore only discards already-expired sessions, which is safe and is what Adobe Commerce documents for the session store. An allkeys-* policy ignores TTLs and will discard a live session under memory pressure, dropping the customer's cart mid-checkout.",
        detection_mechanism: "Reads maxmemory-policy via CONFIG GET (falling back to INFO) and evicted_keys via INFO on the session endpoint.",
        false_positives: "Low for the policy check, which is a definite misconfiguration. The eviction-count half is suppressed when sessions and cache share one instance, because evicted_keys is a server-wide counter that cannot be attributed to the session database alone.",
        verification: "Run in terminal:\n  redis-cli -h <session_host> CONFIG GET maxmemory-policy\n  redis-cli -h <session_host> INFO stats | grep evicted_keys",
        remediation: "Set the session instance to 'volatile-lru', or to 'noeviction' with enough maxmemory to hold peak concurrent sessions. Never use allkeys-* for sessions. Give sessions a dedicated instance so cache churn cannot pressure them.",
    },
    RuleExplanation {
        rule_id: "MD-RDS-002",
        title: "Redis Memory Pressure or Severe Fragmentation",
        what: "The cache instance is above 90% of maxmemory, or its mem_fragmentation_ratio exceeds 1.8 while holding more than 100MB.",
        why_affected: "At the maxmemory ceiling Redis evicts or rejects writes, collapsing the cache hit ratio. High fragmentation means the allocator holds far more RSS than the dataset needs, which invites OS swapping and an OOM kill of the Redis daemon.",
        detection_mechanism: "Reads used_memory, maxmemory and mem_fragmentation_ratio from INFO on the default cache endpoint.",
        false_positives: "Moderate. A fragmentation ratio is unreliable immediately after a large key eviction or a flush, and a ratio below 1.0 simply means part of the dataset has been swapped out. Re-check after a few minutes of steady traffic.",
        verification: "Run in terminal:\n  redis-cli -h <cache_host> INFO memory",
        remediation: "Enable active defragmentation (CONFIG SET activedefrag yes), raise maxmemory, or restart Redis during a maintenance window to compact memory.",
    },
    RuleExplanation {
        rule_id: "MD-RDS-003",
        title: "Low Redis Cache Hit Ratio (Cache Thrashing)",
        what: "The cache instance reports a keyspace hit ratio below 70% over more than 5,000 lookups.",
        why_affected: "Every cache miss falls through to MySQL and full PHP execution. A sustained low hit ratio means the cache is being flushed or evicted faster than it is being filled.",
        detection_mechanism: "Computes keyspace_hits / (keyspace_hits + keyspace_misses) from INFO stats.",
        false_positives: "Moderate. These counters are cumulative since the instance started, so a recent deploy, cache flush, or a freshly started instance will show a low ratio that recovers on its own.",
        verification: "Run in terminal:\n  redis-cli -h <cache_host> INFO stats | grep keyspace",
        remediation: "Look for over-eager cache flushing in deploy scripts or custom code, raise maxmemory, and review cache tag invalidation breadth.",
    },
    RuleExplanation {
        rule_id: "MD-FPM-001",
        title: "PHP-FPM Worker Pool Saturation",
        what: "The PHP-FPM status page reports active workers above 85% of the pool ceiling, a non-empty listen queue, or a non-zero cumulative 'max children reached' counter.",
        why_affected: "When every worker is busy, new requests wait in the listen queue. Once they wait longer than Nginx's proxy_read_timeout the visitor receives a 504.",
        detection_mechanism: "Reads PHP-FPM's own status page (pm.status_path), locally or on a remote node via --fpm-status. This rule deliberately does not fire on /proc-derived numbers: a worker blocked on MySQL or an outbound HTTP call is asleep rather than running, so a /proc scan both under-reports saturation and cannot see the listen queue at all.",
        false_positives: "Low from the status page. A brief spike during cache warming or a deploy is not a standing problem; a persistently non-empty queue is.",
        verification: "Enable pm.status_path in the pool config, then:\n  curl -s 'http://127.0.0.1/status?json'",
        remediation: "Increase pm.max_children if RAM permits (check MD-FPM-002 first), or optimize the slow database queries and external HTTP calls holding workers open.",
    },
    RuleExplanation {
        rule_id: "MD-FPM-002",
        title: "PHP-FPM Pool Memory Allocation Exceeds Host RAM (OOM Risk)",
        what: "pm.max_children multiplied by the measured average worker footprint exceeds 80% of the host's physical memory.",
        why_affected: "pm.max_children is a promise the host may not be able to keep. If traffic ever fills the pool, the Linux OOM killer terminates php-fpm or MySQL, taking the store down rather than merely slowing it.",
        detection_mechanism: "Multiplies pm.max_children from the pool config by the average worker RSS read from /proc, against MemTotal from /proc/meminfo. All three must be real readings: with no pool config, no worker to measure, or no host memory figure, no verdict is issued.",
        false_positives: "Low where all inputs are measured. When no worker was running, the footprint falls back to a documented 150MB estimate, and the finding says so — confirm against your own peak RSS before resizing.",
        verification: "Measure real worker memory:\n  ps -o rss= -C php-fpm | awk '{sum+=$1} END {print sum/NR/1024\" MB avg\"}'",
        remediation: "Lower pm.max_children so the pool ceiling stays under about 75% of physical memory, or add RAM. Reserve headroom for MySQL, Redis and the OS page cache.",
    },
    RuleExplanation {
        rule_id: "MD-FPC-001",
        title: "Storefront Layout FPC Puncture (cacheable=\"false\")",
        what: "A storefront layout XML file (catalog, cms, or default handle) contains a <block> declared with cacheable=\"false\".",
        why_affected: "In Magento 2, setting cacheable=\"false\" on ANY block in a layout completely disables Full Page Cache for that entire page. Every visitor hit then triggers full PHP bootstrapping and tens of database queries.",
        detection_mechanism: "Parses layout XML in every module's view/frontend/layout and view/base/layout trees, plus theme overrides under app/design, flagging blocks with cacheable=\"false\" on storefront handles. Duplicate declarations of one block are reported once.",
        false_positives: "Low. Adobe documents cacheable=\"false\" as unsuitable for cacheable page types. Note that checkout, cart and customer account handles are excluded, since those routes are not FPC-cached anyway.",
        verification: "Run in terminal:\n  curl -I -H 'X-Magento-Cache-Debug: 1' https://your-store.com/<product-url>\nCheck whether X-Magento-Cache-Debug reports MISS on repeated hits.",
        remediation: "Remove cacheable=\"false\" from the layout XML. Move customer-specific content into private customer data (customer-data.js) or load it asynchronously via GraphQL.",
    },
    RuleExplanation {
        rule_id: "MD-SRC-001",
        title: "OpenSearch Cluster Health Degraded",
        what: "Cluster health is red, or the cluster is yellow / has unassigned shards while running more than one node.",
        why_affected: "A red cluster cannot serve search or aggregation queries, producing 500 errors across category and product listing pages. Unassigned shards on a multi-node cluster mean replica redundancy has been lost.",
        detection_mechanism: "Reads GET /_cluster/health and checks status, unassigned_shards and number_of_nodes.",
        false_positives: "Low. Single-node clusters are excluded: they are permanently yellow because replica shards have nowhere to go, and are reported as MD-SRC-002 instead. A cluster mid-rebalance after a restart may report unassigned shards briefly.",
        verification: "Run in terminal:\n  curl -s 'http://localhost:9200/_cluster/health?pretty'\n  curl -s 'http://localhost:9200/_cluster/allocation/explain?pretty'",
        remediation: "Investigate unassigned shards via GET /_cluster/allocation/explain and check disk space and watermark settings on the data nodes.",
    },
    RuleExplanation {
        rule_id: "MD-SRC-002",
        title: "Single-Node OpenSearch Cluster Has No Replica Redundancy",
        what: "The cluster reports yellow purely because it runs on one node, so replica shards cannot be allocated.",
        why_affected: "This is expected for a single-node deployment rather than a fault, but it does mean losing the search node takes catalog search down with no failover.",
        detection_mechanism: "Reads GET /_cluster/health and recognises yellow with number_of_nodes <= 1 as by-design rather than degradation.",
        false_positives: "None; this is informational.",
        verification: "Run in terminal:\n  curl -s 'http://localhost:9200/_cluster/health?pretty'",
        remediation: "Acceptable for staging. For production resilience add a second data node, or set number_of_replicas to 0 so the green/yellow signal becomes meaningful again.",
    },
    RuleExplanation {
        rule_id: "MD-SRC-003",
        title: "No Magento Catalog Search Index Present",
        what: "The cluster is reachable and its index listing was read successfully, but it contains no product or category index.",
        why_affected: "Without a catalog index, search and layered navigation raise search adapter exceptions, breaking category listing pages.",
        detection_mechanism: "Lists indices via GET /_cat/indices and matches Magento's catalog naming (product/category suffixes and catalogsearch_fulltext) rather than a hardcoded 'magento2' prefix, since elasticsearch_index_prefix is configurable. If the listing cannot be read, index presence is treated as unknown and no finding is raised.",
        false_positives: "Low. The rule is suppressed entirely when the index listing probe fails, so an authenticated cluster reachable only with credentials is never reported as empty.",
        verification: "Run in terminal:\n  curl -s 'http://localhost:9200/_cat/indices?v'",
        remediation: "Run bin/magento indexer:reindex catalogsearch_fulltext, and confirm the configured index prefix matches what the cluster holds.",
    },
];

pub fn get_rule_explanation(rule_id: &str) -> Option<&'static RuleExplanation> {
    RULE_EXPLANATIONS.iter().find(|e| e.rule_id.eq_ignore_ascii_case(rule_id))
}
